services:
  bot:
    build: 
      context: . 
      dockerfile: Dockerfile 
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app


  celery_worker:
    build: .
    working_dir: /app/src
    command: ["celery", "-A", "main", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: ["celery", "-A", "main", "beat", "--loglevel=info"]
    working_dir: /app/src
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db: 
    image: postgres:16
    restart: always 
    env_file:
      - .env
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    ports: 
      - "5432:5432" 

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8081:80"  
    depends_on:
      - db

  redis:
    image: redis:7
    restart: always 
    ports:
      - "6379:6379"

  flower:
    build: .
    working_dir: /app/src
    command: celery -A main flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
  flower_data:
