"""init

Revision ID: f15fe81e7509
Revises: 
Create Date: 2025-10-27 16:13:04.923878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15fe81e7509'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('user_notify_task',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('notify_param', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('pair',
    sa.Column('pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dis', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('edworkkind', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('notification_settings',
    sa.Column('notification_settings_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min5', sa.Boolean(), nullable=True),
    sa.Column('min10', sa.Boolean(), nullable=True),
    sa.Column('min15', sa.Boolean(), nullable=True),
    sa.Column('start_pair', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_settings_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_settings')
    op.drop_table('user')
    op.drop_table('pair')
    op.drop_table('user_notify_task')
    op.drop_table('group')
    # ### end Alembic commands ###
